### ISSUE TITLE
Empty result page on finish without starting

### ISSUE THREAD

**Issue by sydneyitguy** [ggomaeng/persecond#4]
![image](https://user-images.githubusercontent.com/1332279/216468750-c48a10b7-a266-4ece-ba64-1842b8844c1c.png)

**Comment by ggomaeng** [comment]
Fixed 4570f12

**Comment by tonynotmorty** [comment]
<img width="620" alt="Screen Shot 2023-02-03 at 14 22 30" src="https://user-images.githubusercontent.com/66512584/216519192-05fb51f6-0f4b-49d7-8ca6-f17d06af8b76.png">
